# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jpereiratrindade/dev/cpp/IdeaWalker

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jpereiratrindade/dev/cpp/IdeaWalker

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jpereiratrindade/dev/cpp/IdeaWalker/CMakeFiles /home/jpereiratrindade/dev/cpp/IdeaWalker//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jpereiratrindade/dev/cpp/IdeaWalker/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named imnodes

# Build rule for target.
imnodes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imnodes
.PHONY : imnodes

# fast build rule for target.
imnodes/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imnodes.dir/build.make CMakeFiles/imnodes.dir/build
.PHONY : imnodes/fast

#=============================================================================
# Target rules for targets named IdeaWalker

# Build rule for target.
IdeaWalker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IdeaWalker
.PHONY : IdeaWalker

# fast build rule for target.
IdeaWalker/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/build
.PHONY : IdeaWalker/fast

#=============================================================================
# Target rules for targets named ideawalker_test

# Build rule for target.
ideawalker_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ideawalker_test
.PHONY : ideawalker_test

# fast build rule for target.
ideawalker_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ideawalker_test.dir/build.make CMakeFiles/ideawalker_test.dir/build
.PHONY : ideawalker_test/fast

#=============================================================================
# Target rules for targets named whisper

# Build rule for target.
whisper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 whisper
.PHONY : whisper

# fast build rule for target.
whisper/fast:
	$(MAKE) $(MAKESILENT) -f _deps/whisper-build/CMakeFiles/whisper.dir/build.make _deps/whisper-build/CMakeFiles/whisper.dir/build
.PHONY : whisper/fast

_deps/imgui-src/backends/imgui_impl_opengl3.o: _deps/imgui-src/backends/imgui_impl_opengl3.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_opengl3.o

# target to build an object file
_deps/imgui-src/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/backends/imgui_impl_opengl3.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_opengl3.cpp.o

_deps/imgui-src/backends/imgui_impl_opengl3.i: _deps/imgui-src/backends/imgui_impl_opengl3.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_opengl3.i

# target to preprocess a source file
_deps/imgui-src/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/backends/imgui_impl_opengl3.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_opengl3.cpp.i

_deps/imgui-src/backends/imgui_impl_opengl3.s: _deps/imgui-src/backends/imgui_impl_opengl3.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
_deps/imgui-src/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/backends/imgui_impl_opengl3.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_opengl3.cpp.s

_deps/imgui-src/backends/imgui_impl_sdl2.o: _deps/imgui-src/backends/imgui_impl_sdl2.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl2.o

# target to build an object file
_deps/imgui-src/backends/imgui_impl_sdl2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/backends/imgui_impl_sdl2.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl2.cpp.o

_deps/imgui-src/backends/imgui_impl_sdl2.i: _deps/imgui-src/backends/imgui_impl_sdl2.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl2.i

# target to preprocess a source file
_deps/imgui-src/backends/imgui_impl_sdl2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/backends/imgui_impl_sdl2.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl2.cpp.i

_deps/imgui-src/backends/imgui_impl_sdl2.s: _deps/imgui-src/backends/imgui_impl_sdl2.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl2.s

# target to generate assembly for a file
_deps/imgui-src/backends/imgui_impl_sdl2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/backends/imgui_impl_sdl2.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl2.cpp.s

_deps/imgui-src/imgui.o: _deps/imgui-src/imgui.cpp.o
.PHONY : _deps/imgui-src/imgui.o

# target to build an object file
_deps/imgui-src/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui.cpp.o
.PHONY : _deps/imgui-src/imgui.cpp.o

_deps/imgui-src/imgui.i: _deps/imgui-src/imgui.cpp.i
.PHONY : _deps/imgui-src/imgui.i

# target to preprocess a source file
_deps/imgui-src/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui.cpp.i
.PHONY : _deps/imgui-src/imgui.cpp.i

_deps/imgui-src/imgui.s: _deps/imgui-src/imgui.cpp.s
.PHONY : _deps/imgui-src/imgui.s

# target to generate assembly for a file
_deps/imgui-src/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui.cpp.s
.PHONY : _deps/imgui-src/imgui.cpp.s

_deps/imgui-src/imgui_demo.o: _deps/imgui-src/imgui_demo.cpp.o
.PHONY : _deps/imgui-src/imgui_demo.o

# target to build an object file
_deps/imgui-src/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_demo.cpp.o
.PHONY : _deps/imgui-src/imgui_demo.cpp.o

_deps/imgui-src/imgui_demo.i: _deps/imgui-src/imgui_demo.cpp.i
.PHONY : _deps/imgui-src/imgui_demo.i

# target to preprocess a source file
_deps/imgui-src/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_demo.cpp.i
.PHONY : _deps/imgui-src/imgui_demo.cpp.i

_deps/imgui-src/imgui_demo.s: _deps/imgui-src/imgui_demo.cpp.s
.PHONY : _deps/imgui-src/imgui_demo.s

# target to generate assembly for a file
_deps/imgui-src/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_demo.cpp.s
.PHONY : _deps/imgui-src/imgui_demo.cpp.s

_deps/imgui-src/imgui_draw.o: _deps/imgui-src/imgui_draw.cpp.o
.PHONY : _deps/imgui-src/imgui_draw.o

# target to build an object file
_deps/imgui-src/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_draw.cpp.o
.PHONY : _deps/imgui-src/imgui_draw.cpp.o

_deps/imgui-src/imgui_draw.i: _deps/imgui-src/imgui_draw.cpp.i
.PHONY : _deps/imgui-src/imgui_draw.i

# target to preprocess a source file
_deps/imgui-src/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_draw.cpp.i
.PHONY : _deps/imgui-src/imgui_draw.cpp.i

_deps/imgui-src/imgui_draw.s: _deps/imgui-src/imgui_draw.cpp.s
.PHONY : _deps/imgui-src/imgui_draw.s

# target to generate assembly for a file
_deps/imgui-src/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_draw.cpp.s
.PHONY : _deps/imgui-src/imgui_draw.cpp.s

_deps/imgui-src/imgui_tables.o: _deps/imgui-src/imgui_tables.cpp.o
.PHONY : _deps/imgui-src/imgui_tables.o

# target to build an object file
_deps/imgui-src/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_tables.cpp.o
.PHONY : _deps/imgui-src/imgui_tables.cpp.o

_deps/imgui-src/imgui_tables.i: _deps/imgui-src/imgui_tables.cpp.i
.PHONY : _deps/imgui-src/imgui_tables.i

# target to preprocess a source file
_deps/imgui-src/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_tables.cpp.i
.PHONY : _deps/imgui-src/imgui_tables.cpp.i

_deps/imgui-src/imgui_tables.s: _deps/imgui-src/imgui_tables.cpp.s
.PHONY : _deps/imgui-src/imgui_tables.s

# target to generate assembly for a file
_deps/imgui-src/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_tables.cpp.s
.PHONY : _deps/imgui-src/imgui_tables.cpp.s

_deps/imgui-src/imgui_widgets.o: _deps/imgui-src/imgui_widgets.cpp.o
.PHONY : _deps/imgui-src/imgui_widgets.o

# target to build an object file
_deps/imgui-src/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_widgets.cpp.o
.PHONY : _deps/imgui-src/imgui_widgets.cpp.o

_deps/imgui-src/imgui_widgets.i: _deps/imgui-src/imgui_widgets.cpp.i
.PHONY : _deps/imgui-src/imgui_widgets.i

# target to preprocess a source file
_deps/imgui-src/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_widgets.cpp.i
.PHONY : _deps/imgui-src/imgui_widgets.cpp.i

_deps/imgui-src/imgui_widgets.s: _deps/imgui-src/imgui_widgets.cpp.s
.PHONY : _deps/imgui-src/imgui_widgets.s

# target to generate assembly for a file
_deps/imgui-src/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_widgets.cpp.s
.PHONY : _deps/imgui-src/imgui_widgets.cpp.s

_deps/imnodes-src/imnodes.o: _deps/imnodes-src/imnodes.cpp.o
.PHONY : _deps/imnodes-src/imnodes.o

# target to build an object file
_deps/imnodes-src/imnodes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imnodes.dir/build.make CMakeFiles/imnodes.dir/_deps/imnodes-src/imnodes.cpp.o
.PHONY : _deps/imnodes-src/imnodes.cpp.o

_deps/imnodes-src/imnodes.i: _deps/imnodes-src/imnodes.cpp.i
.PHONY : _deps/imnodes-src/imnodes.i

# target to preprocess a source file
_deps/imnodes-src/imnodes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imnodes.dir/build.make CMakeFiles/imnodes.dir/_deps/imnodes-src/imnodes.cpp.i
.PHONY : _deps/imnodes-src/imnodes.cpp.i

_deps/imnodes-src/imnodes.s: _deps/imnodes-src/imnodes.cpp.s
.PHONY : _deps/imnodes-src/imnodes.s

# target to generate assembly for a file
_deps/imnodes-src/imnodes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imnodes.dir/build.make CMakeFiles/imnodes.dir/_deps/imnodes-src/imnodes.cpp.s
.PHONY : _deps/imnodes-src/imnodes.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/main.cpp.s
.PHONY : main.cpp.s

src/app/IdeaWalkerApp.o: src/app/IdeaWalkerApp.cpp.o
.PHONY : src/app/IdeaWalkerApp.o

# target to build an object file
src/app/IdeaWalkerApp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/app/IdeaWalkerApp.cpp.o
.PHONY : src/app/IdeaWalkerApp.cpp.o

src/app/IdeaWalkerApp.i: src/app/IdeaWalkerApp.cpp.i
.PHONY : src/app/IdeaWalkerApp.i

# target to preprocess a source file
src/app/IdeaWalkerApp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/app/IdeaWalkerApp.cpp.i
.PHONY : src/app/IdeaWalkerApp.cpp.i

src/app/IdeaWalkerApp.s: src/app/IdeaWalkerApp.cpp.s
.PHONY : src/app/IdeaWalkerApp.s

# target to generate assembly for a file
src/app/IdeaWalkerApp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/app/IdeaWalkerApp.cpp.s
.PHONY : src/app/IdeaWalkerApp.cpp.s

src/application/ContextAssembler.o: src/application/ContextAssembler.cpp.o
.PHONY : src/application/ContextAssembler.o

# target to build an object file
src/application/ContextAssembler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/application/ContextAssembler.cpp.o
.PHONY : src/application/ContextAssembler.cpp.o

src/application/ContextAssembler.i: src/application/ContextAssembler.cpp.i
.PHONY : src/application/ContextAssembler.i

# target to preprocess a source file
src/application/ContextAssembler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/application/ContextAssembler.cpp.i
.PHONY : src/application/ContextAssembler.cpp.i

src/application/ContextAssembler.s: src/application/ContextAssembler.cpp.s
.PHONY : src/application/ContextAssembler.s

# target to generate assembly for a file
src/application/ContextAssembler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/application/ContextAssembler.cpp.s
.PHONY : src/application/ContextAssembler.cpp.s

src/application/ConversationService.o: src/application/ConversationService.cpp.o
.PHONY : src/application/ConversationService.o

# target to build an object file
src/application/ConversationService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/application/ConversationService.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ideawalker_test.dir/build.make CMakeFiles/ideawalker_test.dir/src/application/ConversationService.cpp.o
.PHONY : src/application/ConversationService.cpp.o

src/application/ConversationService.i: src/application/ConversationService.cpp.i
.PHONY : src/application/ConversationService.i

# target to preprocess a source file
src/application/ConversationService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/application/ConversationService.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ideawalker_test.dir/build.make CMakeFiles/ideawalker_test.dir/src/application/ConversationService.cpp.i
.PHONY : src/application/ConversationService.cpp.i

src/application/ConversationService.s: src/application/ConversationService.cpp.s
.PHONY : src/application/ConversationService.s

# target to generate assembly for a file
src/application/ConversationService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/application/ConversationService.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ideawalker_test.dir/build.make CMakeFiles/ideawalker_test.dir/src/application/ConversationService.cpp.s
.PHONY : src/application/ConversationService.cpp.s

src/application/DocumentIngestionService.o: src/application/DocumentIngestionService.cpp.o
.PHONY : src/application/DocumentIngestionService.o

# target to build an object file
src/application/DocumentIngestionService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/application/DocumentIngestionService.cpp.o
.PHONY : src/application/DocumentIngestionService.cpp.o

src/application/DocumentIngestionService.i: src/application/DocumentIngestionService.cpp.i
.PHONY : src/application/DocumentIngestionService.i

# target to preprocess a source file
src/application/DocumentIngestionService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/application/DocumentIngestionService.cpp.i
.PHONY : src/application/DocumentIngestionService.cpp.i

src/application/DocumentIngestionService.s: src/application/DocumentIngestionService.cpp.s
.PHONY : src/application/DocumentIngestionService.s

# target to generate assembly for a file
src/application/DocumentIngestionService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/application/DocumentIngestionService.cpp.s
.PHONY : src/application/DocumentIngestionService.cpp.s

src/application/OrganizerService.o: src/application/OrganizerService.cpp.o
.PHONY : src/application/OrganizerService.o

# target to build an object file
src/application/OrganizerService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/application/OrganizerService.cpp.o
.PHONY : src/application/OrganizerService.cpp.o

src/application/OrganizerService.i: src/application/OrganizerService.cpp.i
.PHONY : src/application/OrganizerService.i

# target to preprocess a source file
src/application/OrganizerService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/application/OrganizerService.cpp.i
.PHONY : src/application/OrganizerService.cpp.i

src/application/OrganizerService.s: src/application/OrganizerService.cpp.s
.PHONY : src/application/OrganizerService.s

# target to generate assembly for a file
src/application/OrganizerService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/application/OrganizerService.cpp.s
.PHONY : src/application/OrganizerService.cpp.s

src/application/SuggestionService.o: src/application/SuggestionService.cpp.o
.PHONY : src/application/SuggestionService.o

# target to build an object file
src/application/SuggestionService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/application/SuggestionService.cpp.o
.PHONY : src/application/SuggestionService.cpp.o

src/application/SuggestionService.i: src/application/SuggestionService.cpp.i
.PHONY : src/application/SuggestionService.i

# target to preprocess a source file
src/application/SuggestionService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/application/SuggestionService.cpp.i
.PHONY : src/application/SuggestionService.cpp.i

src/application/SuggestionService.s: src/application/SuggestionService.cpp.s
.PHONY : src/application/SuggestionService.s

# target to generate assembly for a file
src/application/SuggestionService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/application/SuggestionService.cpp.s
.PHONY : src/application/SuggestionService.cpp.s

src/infrastructure/EmbeddingCache.o: src/infrastructure/EmbeddingCache.cpp.o
.PHONY : src/infrastructure/EmbeddingCache.o

# target to build an object file
src/infrastructure/EmbeddingCache.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/infrastructure/EmbeddingCache.cpp.o
.PHONY : src/infrastructure/EmbeddingCache.cpp.o

src/infrastructure/EmbeddingCache.i: src/infrastructure/EmbeddingCache.cpp.i
.PHONY : src/infrastructure/EmbeddingCache.i

# target to preprocess a source file
src/infrastructure/EmbeddingCache.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/infrastructure/EmbeddingCache.cpp.i
.PHONY : src/infrastructure/EmbeddingCache.cpp.i

src/infrastructure/EmbeddingCache.s: src/infrastructure/EmbeddingCache.cpp.s
.PHONY : src/infrastructure/EmbeddingCache.s

# target to generate assembly for a file
src/infrastructure/EmbeddingCache.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/infrastructure/EmbeddingCache.cpp.s
.PHONY : src/infrastructure/EmbeddingCache.cpp.s

src/infrastructure/FileRepository.o: src/infrastructure/FileRepository.cpp.o
.PHONY : src/infrastructure/FileRepository.o

# target to build an object file
src/infrastructure/FileRepository.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/infrastructure/FileRepository.cpp.o
.PHONY : src/infrastructure/FileRepository.cpp.o

src/infrastructure/FileRepository.i: src/infrastructure/FileRepository.cpp.i
.PHONY : src/infrastructure/FileRepository.i

# target to preprocess a source file
src/infrastructure/FileRepository.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/infrastructure/FileRepository.cpp.i
.PHONY : src/infrastructure/FileRepository.cpp.i

src/infrastructure/FileRepository.s: src/infrastructure/FileRepository.cpp.s
.PHONY : src/infrastructure/FileRepository.s

# target to generate assembly for a file
src/infrastructure/FileRepository.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/infrastructure/FileRepository.cpp.s
.PHONY : src/infrastructure/FileRepository.cpp.s

src/infrastructure/FileSystemArtifactScanner.o: src/infrastructure/FileSystemArtifactScanner.cpp.o
.PHONY : src/infrastructure/FileSystemArtifactScanner.o

# target to build an object file
src/infrastructure/FileSystemArtifactScanner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/infrastructure/FileSystemArtifactScanner.cpp.o
.PHONY : src/infrastructure/FileSystemArtifactScanner.cpp.o

src/infrastructure/FileSystemArtifactScanner.i: src/infrastructure/FileSystemArtifactScanner.cpp.i
.PHONY : src/infrastructure/FileSystemArtifactScanner.i

# target to preprocess a source file
src/infrastructure/FileSystemArtifactScanner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/infrastructure/FileSystemArtifactScanner.cpp.i
.PHONY : src/infrastructure/FileSystemArtifactScanner.cpp.i

src/infrastructure/FileSystemArtifactScanner.s: src/infrastructure/FileSystemArtifactScanner.cpp.s
.PHONY : src/infrastructure/FileSystemArtifactScanner.s

# target to generate assembly for a file
src/infrastructure/FileSystemArtifactScanner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/infrastructure/FileSystemArtifactScanner.cpp.s
.PHONY : src/infrastructure/FileSystemArtifactScanner.cpp.s

src/infrastructure/OllamaAdapter.o: src/infrastructure/OllamaAdapter.cpp.o
.PHONY : src/infrastructure/OllamaAdapter.o

# target to build an object file
src/infrastructure/OllamaAdapter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/infrastructure/OllamaAdapter.cpp.o
.PHONY : src/infrastructure/OllamaAdapter.cpp.o

src/infrastructure/OllamaAdapter.i: src/infrastructure/OllamaAdapter.cpp.i
.PHONY : src/infrastructure/OllamaAdapter.i

# target to preprocess a source file
src/infrastructure/OllamaAdapter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/infrastructure/OllamaAdapter.cpp.i
.PHONY : src/infrastructure/OllamaAdapter.cpp.i

src/infrastructure/OllamaAdapter.s: src/infrastructure/OllamaAdapter.cpp.s
.PHONY : src/infrastructure/OllamaAdapter.s

# target to generate assembly for a file
src/infrastructure/OllamaAdapter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/infrastructure/OllamaAdapter.cpp.s
.PHONY : src/infrastructure/OllamaAdapter.cpp.s

src/infrastructure/PathUtils.o: src/infrastructure/PathUtils.cpp.o
.PHONY : src/infrastructure/PathUtils.o

# target to build an object file
src/infrastructure/PathUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/infrastructure/PathUtils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ideawalker_test.dir/build.make CMakeFiles/ideawalker_test.dir/src/infrastructure/PathUtils.cpp.o
.PHONY : src/infrastructure/PathUtils.cpp.o

src/infrastructure/PathUtils.i: src/infrastructure/PathUtils.cpp.i
.PHONY : src/infrastructure/PathUtils.i

# target to preprocess a source file
src/infrastructure/PathUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/infrastructure/PathUtils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ideawalker_test.dir/build.make CMakeFiles/ideawalker_test.dir/src/infrastructure/PathUtils.cpp.i
.PHONY : src/infrastructure/PathUtils.cpp.i

src/infrastructure/PathUtils.s: src/infrastructure/PathUtils.cpp.s
.PHONY : src/infrastructure/PathUtils.s

# target to generate assembly for a file
src/infrastructure/PathUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/infrastructure/PathUtils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ideawalker_test.dir/build.make CMakeFiles/ideawalker_test.dir/src/infrastructure/PathUtils.cpp.s
.PHONY : src/infrastructure/PathUtils.cpp.s

src/infrastructure/PersistenceService.o: src/infrastructure/PersistenceService.cpp.o
.PHONY : src/infrastructure/PersistenceService.o

# target to build an object file
src/infrastructure/PersistenceService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/infrastructure/PersistenceService.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ideawalker_test.dir/build.make CMakeFiles/ideawalker_test.dir/src/infrastructure/PersistenceService.cpp.o
.PHONY : src/infrastructure/PersistenceService.cpp.o

src/infrastructure/PersistenceService.i: src/infrastructure/PersistenceService.cpp.i
.PHONY : src/infrastructure/PersistenceService.i

# target to preprocess a source file
src/infrastructure/PersistenceService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/infrastructure/PersistenceService.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ideawalker_test.dir/build.make CMakeFiles/ideawalker_test.dir/src/infrastructure/PersistenceService.cpp.i
.PHONY : src/infrastructure/PersistenceService.cpp.i

src/infrastructure/PersistenceService.s: src/infrastructure/PersistenceService.cpp.s
.PHONY : src/infrastructure/PersistenceService.s

# target to generate assembly for a file
src/infrastructure/PersistenceService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/infrastructure/PersistenceService.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ideawalker_test.dir/build.make CMakeFiles/ideawalker_test.dir/src/infrastructure/PersistenceService.cpp.s
.PHONY : src/infrastructure/PersistenceService.cpp.s

src/infrastructure/WhisperCppAdapter.o: src/infrastructure/WhisperCppAdapter.cpp.o
.PHONY : src/infrastructure/WhisperCppAdapter.o

# target to build an object file
src/infrastructure/WhisperCppAdapter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/infrastructure/WhisperCppAdapter.cpp.o
.PHONY : src/infrastructure/WhisperCppAdapter.cpp.o

src/infrastructure/WhisperCppAdapter.i: src/infrastructure/WhisperCppAdapter.cpp.i
.PHONY : src/infrastructure/WhisperCppAdapter.i

# target to preprocess a source file
src/infrastructure/WhisperCppAdapter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/infrastructure/WhisperCppAdapter.cpp.i
.PHONY : src/infrastructure/WhisperCppAdapter.cpp.i

src/infrastructure/WhisperCppAdapter.s: src/infrastructure/WhisperCppAdapter.cpp.s
.PHONY : src/infrastructure/WhisperCppAdapter.s

# target to generate assembly for a file
src/infrastructure/WhisperCppAdapter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/infrastructure/WhisperCppAdapter.cpp.s
.PHONY : src/infrastructure/WhisperCppAdapter.cpp.s

src/test/ConcurrencyTest.o: src/test/ConcurrencyTest.cpp.o
.PHONY : src/test/ConcurrencyTest.o

# target to build an object file
src/test/ConcurrencyTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ideawalker_test.dir/build.make CMakeFiles/ideawalker_test.dir/src/test/ConcurrencyTest.cpp.o
.PHONY : src/test/ConcurrencyTest.cpp.o

src/test/ConcurrencyTest.i: src/test/ConcurrencyTest.cpp.i
.PHONY : src/test/ConcurrencyTest.i

# target to preprocess a source file
src/test/ConcurrencyTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ideawalker_test.dir/build.make CMakeFiles/ideawalker_test.dir/src/test/ConcurrencyTest.cpp.i
.PHONY : src/test/ConcurrencyTest.cpp.i

src/test/ConcurrencyTest.s: src/test/ConcurrencyTest.cpp.s
.PHONY : src/test/ConcurrencyTest.s

# target to generate assembly for a file
src/test/ConcurrencyTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ideawalker_test.dir/build.make CMakeFiles/ideawalker_test.dir/src/test/ConcurrencyTest.cpp.s
.PHONY : src/test/ConcurrencyTest.cpp.s

src/ui/AppState.o: src/ui/AppState.cpp.o
.PHONY : src/ui/AppState.o

# target to build an object file
src/ui/AppState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/ui/AppState.cpp.o
.PHONY : src/ui/AppState.cpp.o

src/ui/AppState.i: src/ui/AppState.cpp.i
.PHONY : src/ui/AppState.i

# target to preprocess a source file
src/ui/AppState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/ui/AppState.cpp.i
.PHONY : src/ui/AppState.cpp.i

src/ui/AppState.s: src/ui/AppState.cpp.s
.PHONY : src/ui/AppState.s

# target to generate assembly for a file
src/ui/AppState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/ui/AppState.cpp.s
.PHONY : src/ui/AppState.cpp.s

src/ui/ConversationPanel.o: src/ui/ConversationPanel.cpp.o
.PHONY : src/ui/ConversationPanel.o

# target to build an object file
src/ui/ConversationPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/ui/ConversationPanel.cpp.o
.PHONY : src/ui/ConversationPanel.cpp.o

src/ui/ConversationPanel.i: src/ui/ConversationPanel.cpp.i
.PHONY : src/ui/ConversationPanel.i

# target to preprocess a source file
src/ui/ConversationPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/ui/ConversationPanel.cpp.i
.PHONY : src/ui/ConversationPanel.cpp.i

src/ui/ConversationPanel.s: src/ui/ConversationPanel.cpp.s
.PHONY : src/ui/ConversationPanel.s

# target to generate assembly for a file
src/ui/ConversationPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/ui/ConversationPanel.cpp.s
.PHONY : src/ui/ConversationPanel.cpp.s

src/ui/UiRenderer.o: src/ui/UiRenderer.cpp.o
.PHONY : src/ui/UiRenderer.o

# target to build an object file
src/ui/UiRenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/ui/UiRenderer.cpp.o
.PHONY : src/ui/UiRenderer.cpp.o

src/ui/UiRenderer.i: src/ui/UiRenderer.cpp.i
.PHONY : src/ui/UiRenderer.i

# target to preprocess a source file
src/ui/UiRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/ui/UiRenderer.cpp.i
.PHONY : src/ui/UiRenderer.cpp.i

src/ui/UiRenderer.s: src/ui/UiRenderer.cpp.s
.PHONY : src/ui/UiRenderer.s

# target to generate assembly for a file
src/ui/UiRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IdeaWalker.dir/build.make CMakeFiles/IdeaWalker.dir/src/ui/UiRenderer.cpp.s
.PHONY : src/ui/UiRenderer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... IdeaWalker"
	@echo "... ideawalker_test"
	@echo "... imgui"
	@echo "... imnodes"
	@echo "... whisper"
	@echo "... _deps/imgui-src/backends/imgui_impl_opengl3.o"
	@echo "... _deps/imgui-src/backends/imgui_impl_opengl3.i"
	@echo "... _deps/imgui-src/backends/imgui_impl_opengl3.s"
	@echo "... _deps/imgui-src/backends/imgui_impl_sdl2.o"
	@echo "... _deps/imgui-src/backends/imgui_impl_sdl2.i"
	@echo "... _deps/imgui-src/backends/imgui_impl_sdl2.s"
	@echo "... _deps/imgui-src/imgui.o"
	@echo "... _deps/imgui-src/imgui.i"
	@echo "... _deps/imgui-src/imgui.s"
	@echo "... _deps/imgui-src/imgui_demo.o"
	@echo "... _deps/imgui-src/imgui_demo.i"
	@echo "... _deps/imgui-src/imgui_demo.s"
	@echo "... _deps/imgui-src/imgui_draw.o"
	@echo "... _deps/imgui-src/imgui_draw.i"
	@echo "... _deps/imgui-src/imgui_draw.s"
	@echo "... _deps/imgui-src/imgui_tables.o"
	@echo "... _deps/imgui-src/imgui_tables.i"
	@echo "... _deps/imgui-src/imgui_tables.s"
	@echo "... _deps/imgui-src/imgui_widgets.o"
	@echo "... _deps/imgui-src/imgui_widgets.i"
	@echo "... _deps/imgui-src/imgui_widgets.s"
	@echo "... _deps/imnodes-src/imnodes.o"
	@echo "... _deps/imnodes-src/imnodes.i"
	@echo "... _deps/imnodes-src/imnodes.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/app/IdeaWalkerApp.o"
	@echo "... src/app/IdeaWalkerApp.i"
	@echo "... src/app/IdeaWalkerApp.s"
	@echo "... src/application/ContextAssembler.o"
	@echo "... src/application/ContextAssembler.i"
	@echo "... src/application/ContextAssembler.s"
	@echo "... src/application/ConversationService.o"
	@echo "... src/application/ConversationService.i"
	@echo "... src/application/ConversationService.s"
	@echo "... src/application/DocumentIngestionService.o"
	@echo "... src/application/DocumentIngestionService.i"
	@echo "... src/application/DocumentIngestionService.s"
	@echo "... src/application/OrganizerService.o"
	@echo "... src/application/OrganizerService.i"
	@echo "... src/application/OrganizerService.s"
	@echo "... src/application/SuggestionService.o"
	@echo "... src/application/SuggestionService.i"
	@echo "... src/application/SuggestionService.s"
	@echo "... src/infrastructure/EmbeddingCache.o"
	@echo "... src/infrastructure/EmbeddingCache.i"
	@echo "... src/infrastructure/EmbeddingCache.s"
	@echo "... src/infrastructure/FileRepository.o"
	@echo "... src/infrastructure/FileRepository.i"
	@echo "... src/infrastructure/FileRepository.s"
	@echo "... src/infrastructure/FileSystemArtifactScanner.o"
	@echo "... src/infrastructure/FileSystemArtifactScanner.i"
	@echo "... src/infrastructure/FileSystemArtifactScanner.s"
	@echo "... src/infrastructure/OllamaAdapter.o"
	@echo "... src/infrastructure/OllamaAdapter.i"
	@echo "... src/infrastructure/OllamaAdapter.s"
	@echo "... src/infrastructure/PathUtils.o"
	@echo "... src/infrastructure/PathUtils.i"
	@echo "... src/infrastructure/PathUtils.s"
	@echo "... src/infrastructure/PersistenceService.o"
	@echo "... src/infrastructure/PersistenceService.i"
	@echo "... src/infrastructure/PersistenceService.s"
	@echo "... src/infrastructure/WhisperCppAdapter.o"
	@echo "... src/infrastructure/WhisperCppAdapter.i"
	@echo "... src/infrastructure/WhisperCppAdapter.s"
	@echo "... src/test/ConcurrencyTest.o"
	@echo "... src/test/ConcurrencyTest.i"
	@echo "... src/test/ConcurrencyTest.s"
	@echo "... src/ui/AppState.o"
	@echo "... src/ui/AppState.i"
	@echo "... src/ui/AppState.s"
	@echo "... src/ui/ConversationPanel.o"
	@echo "... src/ui/ConversationPanel.i"
	@echo "... src/ui/ConversationPanel.s"
	@echo "... src/ui/UiRenderer.o"
	@echo "... src/ui/UiRenderer.i"
	@echo "... src/ui/UiRenderer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

